network:
  version: 2
  ethernets:
    enP4p65s0:
      dhcp4: false
      optional: true
      addresses:
        - 192.168.0.20/24
      routes:
        - to: default
          via: 192.168.0.1
      nameservers:
          addresses: [1.1.1.1, 1.0.0.1]
